### PR TITLE
Optional API host URI configuration

### PR DESCRIPTION
**Pull request by Heehaaw**
Hi, we use your awesome library in a project of ours. It works well and stuff, but we recently stumbled upon an issue where we need to change the API host URL (we started using the enterprise SparkPost solution).
This PR allows the library user to optionally configure said URL through the standard mechanisms.

### CODE REVIEW

**Comment by StrangeWill** [comment]
Hey @Heehaaw, didn't even know that was an option with Enterprise accounts! Thanks. I'll review this and see about pulling it in and having it published this weekend (no promises but I *should* have the time).

**Comment by Heehaaw** [comment]
Hi @StrangeWill, how does it look with the PR? Shall I change something? :)

**Review by StrangeWill — APPROVED** [review]

**Comment by StrangeWill** [comment]
Nope everything looks fine on my end, just dragged my feet on this. Merging and deploying in a little bit.

**Comment by StrangeWill** [comment]
@Heehaaw 0.2.3 has been published with your changes. Thanks for the PR. 😄

**Comment by Heehaaw** [comment]
Thank you very much 👍

**Pull request merged**
